#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI_Database
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Database")]
	public partial class DataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Определения метода расширяемости
    partial void OnCreated();
    partial void InsertPeople(People instance);
    partial void UpdatePeople(People instance);
    partial void DeletePeople(People instance);
    #endregion
		
		public DataClassesDataContext() : 
				base(global::UI_Database.Properties.Settings.Default.DatabaseConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<People> People
		{
			get
			{
				return this.GetTable<People>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.People")]
	public partial class People : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Employee_ID;
		
		private string _Department_ID;
		
		private string _Last_Name;
		
		private string _Sex;
		
		private int _Salary;
		
		private string _Hire_Date;
		
		private System.Nullable<int> _Commision_percent;
		
		private System.Nullable<int> _Income_Tax;
		
		private System.Nullable<int> _Days_Worked;
		
		private System.Nullable<int> _Work_Days_Total;
		
		private System.Nullable<int> _Money_Credited;
		
		private System.Nullable<int> _Money_Witheld;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnEmployee_IDChanging(string value);
    partial void OnEmployee_IDChanged();
    partial void OnDepartment_IDChanging(string value);
    partial void OnDepartment_IDChanged();
    partial void OnLast_NameChanging(string value);
    partial void OnLast_NameChanged();
    partial void OnSexChanging(string value);
    partial void OnSexChanged();
    partial void OnSalaryChanging(int value);
    partial void OnSalaryChanged();
    partial void OnHire_DateChanging(string value);
    partial void OnHire_DateChanged();
    partial void OnCommision_percentChanging(System.Nullable<int> value);
    partial void OnCommision_percentChanged();
    partial void OnIncome_TaxChanging(System.Nullable<int> value);
    partial void OnIncome_TaxChanged();
    partial void OnDays_WorkedChanging(System.Nullable<int> value);
    partial void OnDays_WorkedChanged();
    partial void OnWork_Days_TotalChanging(System.Nullable<int> value);
    partial void OnWork_Days_TotalChanged();
    partial void OnMoney_CreditedChanging(System.Nullable<int> value);
    partial void OnMoney_CreditedChanged();
    partial void OnMoney_WitheldChanging(System.Nullable<int> value);
    partial void OnMoney_WitheldChanged();
    #endregion
		
		public People()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Employee_ID", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Employee_ID
		{
			get
			{
				return this._Employee_ID;
			}
			set
			{
				if ((this._Employee_ID != value))
				{
					this.OnEmployee_IDChanging(value);
					this.SendPropertyChanging();
					this._Employee_ID = value;
					this.SendPropertyChanged("Employee_ID");
					this.OnEmployee_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Department_ID", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string Department_ID
		{
			get
			{
				return this._Department_ID;
			}
			set
			{
				if ((this._Department_ID != value))
				{
					this.OnDepartment_IDChanging(value);
					this.SendPropertyChanging();
					this._Department_ID = value;
					this.SendPropertyChanged("Department_ID");
					this.OnDepartment_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Last_Name", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string Last_Name
		{
			get
			{
				return this._Last_Name;
			}
			set
			{
				if ((this._Last_Name != value))
				{
					this.OnLast_NameChanging(value);
					this.SendPropertyChanging();
					this._Last_Name = value;
					this.SendPropertyChanged("Last_Name");
					this.OnLast_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sex", DbType="NVarChar(10)")]
		public string Sex
		{
			get
			{
				return this._Sex;
			}
			set
			{
				if ((this._Sex != value))
				{
					this.OnSexChanging(value);
					this.SendPropertyChanging();
					this._Sex = value;
					this.SendPropertyChanged("Sex");
					this.OnSexChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Salary", DbType="Int NOT NULL")]
		public int Salary
		{
			get
			{
				return this._Salary;
			}
			set
			{
				if ((this._Salary != value))
				{
					this.OnSalaryChanging(value);
					this.SendPropertyChanging();
					this._Salary = value;
					this.SendPropertyChanged("Salary");
					this.OnSalaryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hire_Date", DbType="NVarChar(10)")]
		public string Hire_Date
		{
			get
			{
				return this._Hire_Date;
			}
			set
			{
				if ((this._Hire_Date != value))
				{
					this.OnHire_DateChanging(value);
					this.SendPropertyChanging();
					this._Hire_Date = value;
					this.SendPropertyChanged("Hire_Date");
					this.OnHire_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Commision_percent", DbType="Int")]
		public System.Nullable<int> Commision_percent
		{
			get
			{
				return this._Commision_percent;
			}
			set
			{
				if ((this._Commision_percent != value))
				{
					this.OnCommision_percentChanging(value);
					this.SendPropertyChanging();
					this._Commision_percent = value;
					this.SendPropertyChanged("Commision_percent");
					this.OnCommision_percentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Income_Tax", DbType="Int")]
		public System.Nullable<int> Income_Tax
		{
			get
			{
				return this._Income_Tax;
			}
			set
			{
				if ((this._Income_Tax != value))
				{
					this.OnIncome_TaxChanging(value);
					this.SendPropertyChanging();
					this._Income_Tax = value;
					this.SendPropertyChanged("Income_Tax");
					this.OnIncome_TaxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Days_Worked", DbType="Int")]
		public System.Nullable<int> Days_Worked
		{
			get
			{
				return this._Days_Worked;
			}
			set
			{
				if ((this._Days_Worked != value))
				{
					this.OnDays_WorkedChanging(value);
					this.SendPropertyChanging();
					this._Days_Worked = value;
					this.SendPropertyChanged("Days_Worked");
					this.OnDays_WorkedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Work_Days_Total", DbType="Int")]
		public System.Nullable<int> Work_Days_Total
		{
			get
			{
				return this._Work_Days_Total;
			}
			set
			{
				if ((this._Work_Days_Total != value))
				{
					this.OnWork_Days_TotalChanging(value);
					this.SendPropertyChanging();
					this._Work_Days_Total = value;
					this.SendPropertyChanged("Work_Days_Total");
					this.OnWork_Days_TotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Money_Credited", DbType="Int")]
		public System.Nullable<int> Money_Credited
		{
			get
			{
				return this._Money_Credited;
			}
			set
			{
				if ((this._Money_Credited != value))
				{
					this.OnMoney_CreditedChanging(value);
					this.SendPropertyChanging();
					this._Money_Credited = value;
					this.SendPropertyChanged("Money_Credited");
					this.OnMoney_CreditedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Money_Witheld", DbType="Int")]
		public System.Nullable<int> Money_Witheld
		{
			get
			{
				return this._Money_Witheld;
			}
			set
			{
				if ((this._Money_Witheld != value))
				{
					this.OnMoney_WitheldChanging(value);
					this.SendPropertyChanging();
					this._Money_Witheld = value;
					this.SendPropertyChanged("Money_Witheld");
					this.OnMoney_WitheldChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
